Recipe and Ingredient Catalogue Report
=========================================

Recipes:
Name: Test Recipe 1, Cuisine: Italian, Average Rating: 2.6
Name: Test Recipe 10, Cuisine: French, Average Rating: 3.2
Name: Test Recipe 100, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 101, Cuisine: Italian, Average Rating: 2.2
Name: Test Recipe 102, Cuisine: Mexican, Average Rating: 2.7
Name: Test Recipe 103, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 104, Cuisine: Indian, Average Rating: 1.0
Name: Test Recipe 105, Cuisine: French, Average Rating: 5.0
Name: Test Recipe 106, Cuisine: Italian, Average Rating: 2.8
Name: Test Recipe 107, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 108, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 109, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 11, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 110, Cuisine: French, Average Rating: 2.7
Name: Test Recipe 111, Cuisine: Italian, Average Rating: 2.7
Name: Test Recipe 112, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 113, Cuisine: Chinese, Average Rating: 3.8
Name: Test Recipe 114, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 115, Cuisine: French, Average Rating: 2.7
Name: Test Recipe 116, Cuisine: Italian, Average Rating: 4.6
Name: Test Recipe 117, Cuisine: Mexican, Average Rating: 2.2
Name: Test Recipe 118, Cuisine: Chinese, Average Rating: 2.3
Name: Test Recipe 119, Cuisine: Indian, Average Rating: 2.8
Name: Test Recipe 12, Cuisine: Mexican, Average Rating: 3.2
Name: Test Recipe 120, Cuisine: French, Average Rating: 2.6
Name: Test Recipe 121, Cuisine: Italian, Average Rating: 3.5
Name: Test Recipe 122, Cuisine: Mexican, Average Rating: 3.7
Name: Test Recipe 123, Cuisine: Chinese, Average Rating: 3.8
Name: Test Recipe 124, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 125, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 126, Cuisine: Italian, Average Rating: 2.5
Name: Test Recipe 127, Cuisine: Mexican, Average Rating: 3.3
Name: Test Recipe 128, Cuisine: Chinese, Average Rating: 2.8
Name: Test Recipe 129, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 13, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 130, Cuisine: French, Average Rating: 2.5
Name: Test Recipe 131, Cuisine: Italian, Average Rating: 4.0
Name: Test Recipe 132, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 133, Cuisine: Chinese, Average Rating: 2.0
Name: Test Recipe 134, Cuisine: Indian, Average Rating: 1.0
Name: Test Recipe 135, Cuisine: French, Average Rating: 4.5
Name: Test Recipe 136, Cuisine: Italian, Average Rating: 2.7
Name: Test Recipe 137, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 138, Cuisine: Chinese, Average Rating: 1.5
Name: Test Recipe 139, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 14, Cuisine: Indian, Average Rating: 3.8
Name: Test Recipe 140, Cuisine: French, Average Rating: 2.7
Name: Test Recipe 141, Cuisine: Italian, Average Rating: 3.2
Name: Test Recipe 142, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 143, Cuisine: Chinese, Average Rating: 3.2
Name: Test Recipe 144, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 145, Cuisine: French, Average Rating: 3.2
Name: Test Recipe 146, Cuisine: Italian, Average Rating: 2.8
Name: Test Recipe 147, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 148, Cuisine: Chinese, Average Rating: 2.0
Name: Test Recipe 149, Cuisine: Indian, Average Rating: 2.4
Name: Test Recipe 15, Cuisine: French, Average Rating: 3.2
Name: Test Recipe 150, Cuisine: French, Average Rating: 2.3
Name: Test Recipe 151, Cuisine: Italian, Average Rating: 4.0
Name: Test Recipe 152, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 153, Cuisine: Chinese, Average Rating: 2.0
Name: Test Recipe 154, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 155, Cuisine: French, Average Rating: 2.8
Name: Test Recipe 156, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 157, Cuisine: Mexican, Average Rating: 5.0
Name: Test Recipe 158, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 159, Cuisine: Indian, Average Rating: 1.5
Name: Test Recipe 16, Cuisine: Italian, Average Rating: 3.2
Name: Test Recipe 160, Cuisine: French, Average Rating: 5.0
Name: Test Recipe 161, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 162, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 163, Cuisine: Chinese, Average Rating: 2.0
Name: Test Recipe 164, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 165, Cuisine: French, Average Rating: 3.2
Name: Test Recipe 166, Cuisine: Italian, Average Rating: 3.6
Name: Test Recipe 167, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 168, Cuisine: Chinese, Average Rating: 4.0
Name: Test Recipe 169, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 17, Cuisine: Mexican, Average Rating: 3.3
Name: Test Recipe 170, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 171, Cuisine: Italian, Average Rating: 2.3
Name: Test Recipe 172, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 173, Cuisine: Chinese, Average Rating: 5.0
Name: Test Recipe 174, Cuisine: Indian, Average Rating: 3.3
Name: Test Recipe 175, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 176, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 177, Cuisine: Mexican, Average Rating: 3.2
Name: Test Recipe 178, Cuisine: Chinese, Average Rating: 2.6
Name: Test Recipe 179, Cuisine: Indian, Average Rating: 2.5
Name: Test Recipe 18, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 180, Cuisine: French, Average Rating: 2.7
Name: Test Recipe 181, Cuisine: Italian, Average Rating: 1.0
Name: Test Recipe 182, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 183, Cuisine: Chinese, Average Rating: 4.0
Name: Test Recipe 184, Cuisine: Indian, Average Rating: 3.3
Name: Test Recipe 185, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 186, Cuisine: Italian, Average Rating: 3.3
Name: Test Recipe 187, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 188, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 189, Cuisine: Indian, Average Rating: 2.7
Name: Test Recipe 19, Cuisine: Indian, Average Rating: 3.5
Name: Test Recipe 190, Cuisine: French, Average Rating: 4.2
Name: Test Recipe 191, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 192, Cuisine: Mexican, Average Rating: 2.4
Name: Test Recipe 193, Cuisine: Chinese, Average Rating: 2.2
Name: Test Recipe 194, Cuisine: Indian, Average Rating: 1.0
Name: Test Recipe 195, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 196, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 197, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 198, Cuisine: Chinese, Average Rating: 2.2
Name: Test Recipe 199, Cuisine: Indian, Average Rating: 4.5
Name: Test Recipe 2, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 20, Cuisine: French, Average Rating: 4.3
Name: Test Recipe 200, Cuisine: French, Average Rating: 3.2
Name: Test Recipe 201, Cuisine: Italian, Average Rating: 2.5
Name: Test Recipe 202, Cuisine: Mexican, Average Rating: 2.2
Name: Test Recipe 203, Cuisine: Chinese, Average Rating: 1.5
Name: Test Recipe 204, Cuisine: Indian, Average Rating: 3.5
Name: Test Recipe 205, Cuisine: French, Average Rating: 2.8
Name: Test Recipe 206, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 207, Cuisine: Mexican, Average Rating: 2.7
Name: Test Recipe 208, Cuisine: Chinese, Average Rating: 2.7
Name: Test Recipe 209, Cuisine: Indian, Average Rating: 2.3
Name: Test Recipe 21, Cuisine: Italian, Average Rating: 4.3
Name: Test Recipe 210, Cuisine: French, Average Rating: 2.3
Name: Test Recipe 211, Cuisine: Italian, Average Rating: 3.5
Name: Test Recipe 212, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 213, Cuisine: Chinese, Average Rating: 5.0
Name: Test Recipe 214, Cuisine: Indian, Average Rating: 2.8
Name: Test Recipe 215, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 216, Cuisine: Italian, Average Rating: 3.8
Name: Test Recipe 217, Cuisine: Mexican, Average Rating: 2.7
Name: Test Recipe 218, Cuisine: Chinese, Average Rating: 4.0
Name: Test Recipe 219, Cuisine: Indian, Average Rating: 3.8
Name: Test Recipe 22, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 220, Cuisine: French, Average Rating: 2.8
Name: Test Recipe 221, Cuisine: Italian, Average Rating: 4.2
Name: Test Recipe 222, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 223, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 224, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 225, Cuisine: French, Average Rating: 1.0
Name: Test Recipe 226, Cuisine: Italian, Average Rating: 3.7
Name: Test Recipe 227, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 228, Cuisine: Chinese, Average Rating: 3.5
Name: Test Recipe 229, Cuisine: Indian, Average Rating: 2.5
Name: Test Recipe 23, Cuisine: Chinese, Average Rating: 2.8
Name: Test Recipe 230, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 231, Cuisine: Italian, Average Rating: 3.6
Name: Test Recipe 232, Cuisine: Mexican, Average Rating: 3.6
Name: Test Recipe 233, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 234, Cuisine: Indian, Average Rating: 2.8
Name: Test Recipe 235, Cuisine: French, Average Rating: 3.5
Name: Test Recipe 236, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 237, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 238, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 239, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 24, Cuisine: Indian, Average Rating: 3.2
Name: Test Recipe 240, Cuisine: French, Average Rating: 3.3
Name: Test Recipe 241, Cuisine: Italian, Average Rating: 3.7
Name: Test Recipe 242, Cuisine: Mexican, Average Rating: 2.5
Name: Test Recipe 243, Cuisine: Chinese, Average Rating: 4.3
Name: Test Recipe 244, Cuisine: Indian, Average Rating: 3.5
Name: Test Recipe 245, Cuisine: French, Average Rating: 1.0
Name: Test Recipe 246, Cuisine: Italian, Average Rating: 2.2
Name: Test Recipe 247, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 248, Cuisine: Chinese, Average Rating: 3.5
Name: Test Recipe 249, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 25, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 250, Cuisine: French, Average Rating: 4.5
Name: Test Recipe 251, Cuisine: Italian, Average Rating: 3.5
Name: Test Recipe 252, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 253, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 254, Cuisine: Indian, Average Rating: 2.5
Name: Test Recipe 255, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 256, Cuisine: Italian, Average Rating: 4.2
Name: Test Recipe 257, Cuisine: Mexican, Average Rating: 2.8
Name: Test Recipe 258, Cuisine: Chinese, Average Rating: 3.3
Name: Test Recipe 259, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 26, Cuisine: Italian, Average Rating: 2.8
Name: Test Recipe 260, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 261, Cuisine: Italian, Average Rating: 1.7
Name: Test Recipe 262, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 263, Cuisine: Chinese, Average Rating: 4.5
Name: Test Recipe 264, Cuisine: Indian, Average Rating: 2.2
Name: Test Recipe 265, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 266, Cuisine: Italian, Average Rating: 3.4
Name: Test Recipe 267, Cuisine: Mexican, Average Rating: 2.5
Name: Test Recipe 268, Cuisine: Chinese, Average Rating: 4.7
Name: Test Recipe 269, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 27, Cuisine: Mexican, Average Rating: 2.8
Name: Test Recipe 270, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 271, Cuisine: Italian, Average Rating: 2.6
Name: Test Recipe 272, Cuisine: Mexican, Average Rating: 3.8
Name: Test Recipe 273, Cuisine: Chinese, Average Rating: 1.5
Name: Test Recipe 274, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 275, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 276, Cuisine: Italian, Average Rating: 2.5
Name: Test Recipe 277, Cuisine: Mexican, Average Rating: 3.2
Name: Test Recipe 278, Cuisine: Chinese, Average Rating: 1.5
Name: Test Recipe 279, Cuisine: Indian, Average Rating: 1.0
Name: Test Recipe 28, Cuisine: Chinese, Average Rating: 1.8
Name: Test Recipe 280, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 281, Cuisine: Italian, Average Rating: 2.8
Name: Test Recipe 282, Cuisine: Mexican, Average Rating: 4.5
Name: Test Recipe 283, Cuisine: Chinese, Average Rating: 3.5
Name: Test Recipe 284, Cuisine: Indian, Average Rating: 3.6
Name: Test Recipe 285, Cuisine: French, Average Rating: 2.8
Name: Test Recipe 286, Cuisine: Italian, Average Rating: 1.0
Name: Test Recipe 287, Cuisine: Mexican, Average Rating: 2.8
Name: Test Recipe 288, Cuisine: Chinese, Average Rating: 4.0
Name: Test Recipe 289, Cuisine: Indian, Average Rating: 3.8
Name: Test Recipe 29, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 290, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 291, Cuisine: Italian, Average Rating: 2.8
Name: Test Recipe 292, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 293, Cuisine: Chinese, Average Rating: 3.6
Name: Test Recipe 294, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 295, Cuisine: French, Average Rating: 3.3
Name: Test Recipe 296, Cuisine: Italian, Average Rating: 2.8
Name: Test Recipe 297, Cuisine: Mexican, Average Rating: 4.5
Name: Test Recipe 298, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 299, Cuisine: Indian, Average Rating: 3.2
Name: Test Recipe 3, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 30, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 300, Cuisine: French, Average Rating: 3.6
Name: Test Recipe 301, Cuisine: Italian, Average Rating: 2.7
Name: Test Recipe 302, Cuisine: Mexican, Average Rating: 1.0
Name: Test Recipe 303, Cuisine: Chinese, Average Rating: 1.5
Name: Test Recipe 304, Cuisine: Indian, Average Rating: 2.8
Name: Test Recipe 305, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 306, Cuisine: Italian, Average Rating: 2.3
Name: Test Recipe 307, Cuisine: Mexican, Average Rating: 2.8
Name: Test Recipe 308, Cuisine: Chinese, Average Rating: 3.8
Name: Test Recipe 309, Cuisine: Indian, Average Rating: 3.5
Name: Test Recipe 31, Cuisine: Italian, Average Rating: 4.0
Name: Test Recipe 310, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 311, Cuisine: Italian, Average Rating: 1.2
Name: Test Recipe 312, Cuisine: Mexican, Average Rating: 3.5
Name: Test Recipe 313, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 314, Cuisine: Indian, Average Rating: 4.5
Name: Test Recipe 315, Cuisine: French, Average Rating: 5.0
Name: Test Recipe 316, Cuisine: Italian, Average Rating: 5.0
Name: Test Recipe 317, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 318, Cuisine: Chinese, Average Rating: 3.8
Name: Test Recipe 319, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 32, Cuisine: Mexican, Average Rating: 2.5
Name: Test Recipe 320, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 321, Cuisine: Italian, Average Rating: 3.5
Name: Test Recipe 322, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 323, Cuisine: Chinese, Average Rating: 2.8
Name: Test Recipe 324, Cuisine: Indian, Average Rating: 2.3
Name: Test Recipe 325, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 326, Cuisine: Italian, Average Rating: 4.0
Name: Test Recipe 327, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 328, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 329, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 33, Cuisine: Chinese, Average Rating: 2.5
Name: Test Recipe 330, Cuisine: French, Average Rating: 3.5
Name: Test Recipe 331, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 332, Cuisine: Mexican, Average Rating: 3.3
Name: Test Recipe 333, Cuisine: Chinese, Average Rating: 1.8
Name: Test Recipe 334, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 335, Cuisine: French, Average Rating: 2.5
Name: Test Recipe 336, Cuisine: Italian, Average Rating: 2.7
Name: Test Recipe 337, Cuisine: Mexican, Average Rating: 2.3
Name: Test Recipe 338, Cuisine: Chinese, Average Rating: 3.2
Name: Test Recipe 339, Cuisine: Indian, Average Rating: 2.8
Name: Test Recipe 34, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 340, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 341, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 342, Cuisine: Mexican, Average Rating: 2.8
Name: Test Recipe 343, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 344, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 345, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 346, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 347, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 348, Cuisine: Chinese, Average Rating: 1.5
Name: Test Recipe 349, Cuisine: Indian, Average Rating: 3.8
Name: Test Recipe 35, Cuisine: French, Average Rating: 3.7
Name: Test Recipe 350, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 351, Cuisine: Italian, Average Rating: 5.0
Name: Test Recipe 352, Cuisine: Mexican, Average Rating: 2.5
Name: Test Recipe 353, Cuisine: Chinese, Average Rating: 3.4
Name: Test Recipe 354, Cuisine: Indian, Average Rating: 3.2
Name: Test Recipe 355, Cuisine: French, Average Rating: 3.5
Name: Test Recipe 356, Cuisine: Italian, Average Rating: 2.6
Name: Test Recipe 357, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 358, Cuisine: Chinese, Average Rating: 4.5
Name: Test Recipe 359, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 36, Cuisine: Italian, Average Rating: 1.0
Name: Test Recipe 360, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 361, Cuisine: Italian, Average Rating: 3.4
Name: Test Recipe 362, Cuisine: Mexican, Average Rating: 3.7
Name: Test Recipe 363, Cuisine: Chinese, Average Rating: 3.2
Name: Test Recipe 364, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 365, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 366, Cuisine: Italian, Average Rating: 4.0
Name: Test Recipe 367, Cuisine: Mexican, Average Rating: 3.2
Name: Test Recipe 368, Cuisine: Chinese, Average Rating: 1.0
Name: Test Recipe 369, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 37, Cuisine: Mexican, Average Rating: 4.7
Name: Test Recipe 370, Cuisine: French, Average Rating: 3.4
Name: Test Recipe 371, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 372, Cuisine: Mexican, Average Rating: 3.5
Name: Test Recipe 373, Cuisine: Chinese, Average Rating: 1.0
Name: Test Recipe 374, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 375, Cuisine: French, Average Rating: 2.4
Name: Test Recipe 376, Cuisine: Italian, Average Rating: 3.8
Name: Test Recipe 377, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 378, Cuisine: Chinese, Average Rating: 2.7
Name: Test Recipe 379, Cuisine: Indian, Average Rating: 3.7
Name: Test Recipe 38, Cuisine: Chinese, Average Rating: 3.8
Name: Test Recipe 380, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 381, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 382, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 383, Cuisine: Chinese, Average Rating: 5.0
Name: Test Recipe 384, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 385, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 386, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 387, Cuisine: Mexican, Average Rating: 3.4
Name: Test Recipe 388, Cuisine: Chinese, Average Rating: 3.6
Name: Test Recipe 389, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 39, Cuisine: Indian, Average Rating: 1.0
Name: Test Recipe 390, Cuisine: French, Average Rating: 1.5
Name: Test Recipe 391, Cuisine: Italian, Average Rating: 2.8
Name: Test Recipe 392, Cuisine: Mexican, Average Rating: 4.5
Name: Test Recipe 393, Cuisine: Chinese, Average Rating: 3.5
Name: Test Recipe 394, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 395, Cuisine: French, Average Rating: 1.0
Name: Test Recipe 396, Cuisine: Italian, Average Rating: 1.0
Name: Test Recipe 397, Cuisine: Mexican, Average Rating: 2.6
Name: Test Recipe 398, Cuisine: Chinese, Average Rating: 3.7
Name: Test Recipe 399, Cuisine: Indian, Average Rating: 3.8
Name: Test Recipe 4, Cuisine: Indian, Average Rating: 1.7
Name: Test Recipe 40, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 400, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 401, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 402, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 403, Cuisine: Chinese, Average Rating: 2.5
Name: Test Recipe 404, Cuisine: Indian, Average Rating: 2.8
Name: Test Recipe 405, Cuisine: French, Average Rating: 2.5
Name: Test Recipe 406, Cuisine: Italian, Average Rating: 1.8
Name: Test Recipe 407, Cuisine: Mexican, Average Rating: 3.5
Name: Test Recipe 408, Cuisine: Chinese, Average Rating: 2.2
Name: Test Recipe 409, Cuisine: Indian, Average Rating: 2.3
Name: Test Recipe 41, Cuisine: Italian, Average Rating: 3.4
Name: Test Recipe 410, Cuisine: French, Average Rating: 4.7
Name: Test Recipe 411, Cuisine: Italian, Average Rating: 2.5
Name: Test Recipe 412, Cuisine: Mexican, Average Rating: 3.7
Name: Test Recipe 413, Cuisine: Chinese, Average Rating: 3.3
Name: Test Recipe 414, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 415, Cuisine: French, Average Rating: 3.5
Name: Test Recipe 416, Cuisine: Italian, Average Rating: 1.2
Name: Test Recipe 417, Cuisine: Mexican, Average Rating: 2.4
Name: Test Recipe 418, Cuisine: Chinese, Average Rating: 4.0
Name: Test Recipe 419, Cuisine: Indian, Average Rating: 2.2
Name: Test Recipe 42, Cuisine: Mexican, Average Rating: 5.0
Name: Test Recipe 420, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 421, Cuisine: Italian, Average Rating: 2.6
Name: Test Recipe 422, Cuisine: Mexican, Average Rating: 3.8
Name: Test Recipe 423, Cuisine: Chinese, Average Rating: 3.3
Name: Test Recipe 424, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 425, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 426, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 427, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 428, Cuisine: Chinese, Average Rating: 3.3
Name: Test Recipe 429, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 43, Cuisine: Chinese, Average Rating: 4.5
Name: Test Recipe 430, Cuisine: French, Average Rating: 1.3
Name: Test Recipe 431, Cuisine: Italian, Average Rating: 1.2
Name: Test Recipe 432, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 433, Cuisine: Chinese, Average Rating: 1.0
Name: Test Recipe 434, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 435, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 436, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 437, Cuisine: Mexican, Average Rating: 1.0
Name: Test Recipe 438, Cuisine: Chinese, Average Rating: 3.6
Name: Test Recipe 439, Cuisine: Indian, Average Rating: 2.3
Name: Test Recipe 44, Cuisine: Indian, Average Rating: 1.7
Name: Test Recipe 440, Cuisine: French, Average Rating: 1.0
Name: Test Recipe 441, Cuisine: Italian, Average Rating: 2.8
Name: Test Recipe 442, Cuisine: Mexican, Average Rating: 4.5
Name: Test Recipe 443, Cuisine: Chinese, Average Rating: 4.0
Name: Test Recipe 444, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 445, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 446, Cuisine: Italian, Average Rating: 2.4
Name: Test Recipe 447, Cuisine: Mexican, Average Rating: 2.5
Name: Test Recipe 448, Cuisine: Chinese, Average Rating: 3.8
Name: Test Recipe 449, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 45, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 450, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 451, Cuisine: Italian, Average Rating: 3.5
Name: Test Recipe 452, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 453, Cuisine: Chinese, Average Rating: 3.7
Name: Test Recipe 454, Cuisine: Indian, Average Rating: 3.3
Name: Test Recipe 455, Cuisine: French, Average Rating: 3.8
Name: Test Recipe 456, Cuisine: Italian, Average Rating: 4.3
Name: Test Recipe 457, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 458, Cuisine: Chinese, Average Rating: 2.6
Name: Test Recipe 459, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 46, Cuisine: Italian, Average Rating: 1.0
Name: Test Recipe 460, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 461, Cuisine: Italian, Average Rating: 3.6
Name: Test Recipe 462, Cuisine: Mexican, Average Rating: 3.5
Name: Test Recipe 463, Cuisine: Chinese, Average Rating: 2.2
Name: Test Recipe 464, Cuisine: Indian, Average Rating: 1.0
Name: Test Recipe 465, Cuisine: French, Average Rating: 2.5
Name: Test Recipe 466, Cuisine: Italian, Average Rating: 4.0
Name: Test Recipe 467, Cuisine: Mexican, Average Rating: 2.6
Name: Test Recipe 468, Cuisine: Chinese, Average Rating: 2.0
Name: Test Recipe 469, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 47, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 470, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 471, Cuisine: Italian, Average Rating: 3.5
Name: Test Recipe 472, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 473, Cuisine: Chinese, Average Rating: 2.0
Name: Test Recipe 474, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 475, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 476, Cuisine: Italian, Average Rating: 2.7
Name: Test Recipe 477, Cuisine: Mexican, Average Rating: 3.6
Name: Test Recipe 478, Cuisine: Chinese, Average Rating: 3.4
Name: Test Recipe 479, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 48, Cuisine: Chinese, Average Rating: 3.5
Name: Test Recipe 480, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 481, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 482, Cuisine: Mexican, Average Rating: 1.5
Name: Test Recipe 483, Cuisine: Chinese, Average Rating: 1.0
Name: Test Recipe 484, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 485, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 486, Cuisine: Italian, Average Rating: 3.2
Name: Test Recipe 487, Cuisine: Mexican, Average Rating: 2.2
Name: Test Recipe 488, Cuisine: Chinese, Average Rating: 2.7
Name: Test Recipe 489, Cuisine: Indian, Average Rating: 2.8
Name: Test Recipe 49, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 490, Cuisine: French, Average Rating: 3.4
Name: Test Recipe 491, Cuisine: Italian, Average Rating: 4.5
Name: Test Recipe 492, Cuisine: Mexican, Average Rating: 2.5
Name: Test Recipe 493, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 494, Cuisine: Indian, Average Rating: 3.4
Name: Test Recipe 495, Cuisine: French, Average Rating: 1.5
Name: Test Recipe 496, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 497, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 498, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 499, Cuisine: Indian, Average Rating: 3.2
Name: Test Recipe 5, Cuisine: French, Average Rating: 2.8
Name: Test Recipe 50, Cuisine: French, Average Rating: 2.0
Name: Test Recipe 500, Cuisine: French, Average Rating: 3.0
Name: Test Recipe 51, Cuisine: Italian, Average Rating: 4.0
Name: Test Recipe 52, Cuisine: Mexican, Average Rating: 1.7
Name: Test Recipe 53, Cuisine: Chinese, Average Rating: 2.8
Name: Test Recipe 54, Cuisine: Indian, Average Rating: 3.7
Name: Test Recipe 55, Cuisine: French, Average Rating: 3.4
Name: Test Recipe 56, Cuisine: Italian, Average Rating: 4.8
Name: Test Recipe 57, Cuisine: Mexican, Average Rating: 2.7
Name: Test Recipe 58, Cuisine: Chinese, Average Rating: 4.0
Name: Test Recipe 59, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 6, Cuisine: Italian, Average Rating: 2.7
Name: Test Recipe 60, Cuisine: French, Average Rating: 3.8
Name: Test Recipe 61, Cuisine: Italian, Average Rating: 2.0
Name: Test Recipe 62, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 63, Cuisine: Chinese, Average Rating: 2.8
Name: Test Recipe 64, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 65, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 66, Cuisine: Italian, Average Rating: 1.0
Name: Test Recipe 67, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 68, Cuisine: Chinese, Average Rating: 1.0
Name: Test Recipe 69, Cuisine: Indian, Average Rating: 3.2
Name: Test Recipe 7, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 70, Cuisine: French, Average Rating: 3.3
Name: Test Recipe 71, Cuisine: Italian, Average Rating: 2.5
Name: Test Recipe 72, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 73, Cuisine: Chinese, Average Rating: 2.7
Name: Test Recipe 74, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 75, Cuisine: French, Average Rating: 2.6
Name: Test Recipe 76, Cuisine: Italian, Average Rating: 4.0
Name: Test Recipe 77, Cuisine: Mexican, Average Rating: 2.0
Name: Test Recipe 78, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 79, Cuisine: Indian, Average Rating: 5.0
Name: Test Recipe 8, Cuisine: Chinese, Average Rating: 2.2
Name: Test Recipe 80, Cuisine: French, Average Rating: 2.8
Name: Test Recipe 81, Cuisine: Italian, Average Rating: 4.7
Name: Test Recipe 82, Cuisine: Mexican, Average Rating: 3.0
Name: Test Recipe 83, Cuisine: Chinese, Average Rating: 3.6
Name: Test Recipe 84, Cuisine: Indian, Average Rating: 3.0
Name: Test Recipe 85, Cuisine: French, Average Rating: 1.3
Name: Test Recipe 86, Cuisine: Italian, Average Rating: 3.0
Name: Test Recipe 87, Cuisine: Mexican, Average Rating: 4.0
Name: Test Recipe 88, Cuisine: Chinese, Average Rating: 2.7
Name: Test Recipe 89, Cuisine: Indian, Average Rating: 2.7
Name: Test Recipe 9, Cuisine: Indian, Average Rating: 4.0
Name: Test Recipe 90, Cuisine: French, Average Rating: 4.0
Name: Test Recipe 91, Cuisine: Italian, Average Rating: 2.5
Name: Test Recipe 92, Cuisine: Mexican, Average Rating: 3.5
Name: Test Recipe 93, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 94, Cuisine: Indian, Average Rating: 2.0
Name: Test Recipe 95, Cuisine: French, Average Rating: 3.3
Name: Test Recipe 96, Cuisine: Italian, Average Rating: 3.5
Name: Test Recipe 97, Cuisine: Mexican, Average Rating: 3.3
Name: Test Recipe 98, Cuisine: Chinese, Average Rating: 3.0
Name: Test Recipe 99, Cuisine: Indian, Average Rating: 3.7

Ingredients:
Name: Beans, Quantity: 180
Name: Beef, Quantity: 160
Name: Cheese, Quantity: 130
Name: Chicken, Quantity: 150
Name: Garlic, Quantity: 120
Name: Onion, Quantity: 110
Name: Pasta, Quantity: 140
Name: Pepper, Quantity: 190
Name: Rice, Quantity: 170
Name: Tomato, Quantity: 100
